### ISSUE TITLE
停止运行（接口执行报错）

### ISSUE THREAD

**Issue by shiguiyang** [baifendian/swordfish#48]
post接口
http://172.24.5.149:12345/executors/:execid/kill
步骤
1.udp直接执行一个任务
2.执行中调用接口停止运行
预期结果 
返回200 udp端任务被kill
实际结果返回
"status": 500,
  "error": "Internal Server Error",
  "message": "Call master client kill workflow false , project id: \"7\", exec flow id: \"373\",host: \"172.24.5.149\", port: \"12,000\""
udp端被kill，但是返回报错信息
INFO] 2017-05-23 17:31:40.231 com.baifendian.swordfish.execserver.runner.node.NodeRunner:[151] -  cancel job:FLOW_373_8216f2a1_8216f2a1, kill process:9042
[WARN] 2017-05-23 17:31:40.233 com.baifendian.swordfish.execserver.runner.node.NodeRunner:[191] -  Kill with signal TERM failed. Killing with KILL signal.
[ERROR] 2017-05-23 17:31:40.237 com.baifendian.swordfish.execserver.runner.node.NodeRunner:[255] -  null
java.lang.InterruptedException: null
	at java.lang.Object.wait(Native Method)
	at java.lang.UNIXProcess.waitFor(UNIXProcess.java:413)
	at com.baifendian.swordfish.execserver.job.AbstractProcessJob.process(AbstractProcessJob.java:160)
	at com.baifendian.swordfish.execserver.runner.node.NodeRunner.call(NodeRunner.java:133)
	at com.baifendian.swordfish.execserver.runner.node.NodeRunner.call(NodeRunner.java:39)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by caojingwei** [comment]
这个是由于通知邮件无法发出导致的，正在处理

**Comment by caojingwei** [comment]
已经解决

**Comment by shiguiyang** [comment]
已修复
